### ISSUE TITLE
support realgud?

### ISSUE THREAD

**Issue by jgarte** [muffinmad/emacs-pdb-capf#3]
Does emacs-pdb-capf work with realgud or have you tested it before?

**Comment by muffinmad** [comment]
Looks like realgud is using `pdb-track-mode` minor mode for pdb debugger process.

So after evaluating this code and running `M-x realgud:pdb`

```elisp
(add-hook 'pdb-track-mode-hook
	  (lambda ()
	    (add-hook 'completion-at-point-functions
		      'pdb-capf nil t)))
```

The result is:
<img width="595" alt="Screenshot 2022-08-09 at 22 57 33" src="https://user-images.githubusercontent.com/2702727/183749849-1493d9e0-d31c-4a03-b023-4d4c5060d60f.png">

**Comment by jgarte** [comment]
Awesome! Should we mention this in the README or link it to realgud somehow?

**Comment by muffinmad** [comment]
I don't think we need to list every comint mode that can be possibly used for pdb. The README contains general example and configuring specific modes is up to user.
